-- app 유저에게 필요한 권한 부여
ALTER DATABASE indexer OWNER TO app;

-- app 유저에게 스키마 생성 권한 부여
ALTER USER app CREATEDB;

-- public 스키마에 대한 권한 부여
GRANT ALL ON SCHEMA public TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app;

-- 향후 생성될 객체들에 대한 권한 부여
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO app;